# ─────────────────────────────────────────────────────────────────
# BP4D+ Dataset – Configurations
# ─────────────────────────────────────────────────────────────────
#
# Expected directory structure:
#   BP4D+/
#   ├── Physiology/
#   │   └── F001/
#   │       └── T1/
#   │           ├── Pulse Rate_BPM.txt
#   │           ├── Respiration Rate_BPM.txt
#   │           ├── BP_mmHg.txt
#   │           ├── BP Dia_mmHg.txt
#   │           ├── LA Mean BP_mmHg.txt
#   │           ├── LA Systolic BP_mmHg.txt
#   │           ├── microsiemens.txt
#   │           └── Resp_Volts.txt
#   └── Thermal/
#       └── F001/
#           ├── T1.wmv
#           └── ...
# ─────────────────────────────────────────────────────────────────

# Path to BP4D+ directory
root_dir: "/Volumes/StudiShare/XDatabase/PPGI/BP4D+_v0.2"

# Subject and task filters
# null = load all available
# List = load only specified entries
subjects: ["F001", "F002"] # e.g. ["F001", "F002"] or null
tasks: ["T1"]                # e.g. ["T1", "T8"] or null

# Video parameters
fps: 25 # Fallback-FPS [frames per second]

# no warm-up required for BP4D+ as camera is already stabilized
warmup_seconds: 0
